#!/bin/sh
STAGING=${S3_STAGING:-/Projects/sites/ideoplex/ideoplex.com}
BUCKET=${S3_BUCKET:-s3://ideoplex.com}
#
SYNC=no
UPDATE=no

case $# in
0) SYNC=yes
   UPDATE=yes;;
1) case $1 in
   sy*) SYNC=yes;;
   up*) UPDATE=yes;;
   esac;;
esac
#
# sync with a default max-age of 30 days
case $SYNC in
yes) s3cmd sync --no-preserve --cf-invalidate --add-header="Cache-Control: public, max-age=2592000" $STAGING/ $BUCKET/ ;;
esac
#
# early exit?
case $UPDATE in
no )   exit 0;;
esac
#
YEAR=$(date +%Y)
MONTH=$(date +%Y/%m)
DAY=$(date +%Y/%m/%d)
#
# 1 hour
s3cmd modify --add-header="Cache-Control: public, max-age=3600" \
      $BUCKET/index.html $BUCKET/atom.xml
s3cmd modify --add-header="Cache-Control: public, max-age=3600" --recursive \
      $BUCKET/categories/ $BUCKET/$DAY/
#
# 1 day
s3cmd modify --add-header="Cache-Control: public, max-age=86400" \
      $BUCKET/sitemap.xml $BUCKET/archives/index.html $BUCKET/archives/$MONTH/index.html $BUCKET/archives/$YEAR/index.html
s3cmd modify --add-header="Cache-Control: public, max-age=86400" --recursive \
      $BUCKET/page/ $BUCKET/tags/
