#!/bin/sh
STAGING=${S3_STAGING:-/Projects/sites/ideoplex/ideoplex.com}
BUCKET=${S3_BUCKET:-s3://ideoplex.com}
#
# sync with a default max-age of 30 days
s3cmd sync --no-preserve --cf-invalidate --add-header="Cache-Control: public, max-age=2592000" \
      $STAGING/ $BUCKET/
#
YEAR=$(date +%Y)
MONTH=$(date +%Y/%m)
DAY=$(date +%Y/%m/%d)
#
# 1 hour
s3cmd modify --add-header="Cache-Control: public, max-age=3600" \
      $BUCKET/index.html $BUCKET/atom.xml
s3cmd modify --add-header="Cache-Control: public, max-age=3600" --recursive \
      $BUCKET/categories/ $BUCKET/$DAY/
#
# 1 day
s3cmd modify --add-header="Cache-Control: public, max-age=86400" \
      $BUCKET/sitemap.xml $BUCKET/archives/index.html $BUCKET/archives/$MONTH/index.html $BUCKET/archives/$YEAR/index.html
s3cmd modify --add-header="Cache-Control: public, max-age=86400" --recursive \
      $BUCKET/page/ $BUCKET/tags/
